/* 
<!-- Eddy Davila -->
<!-- Project 3 -->
<!-- VFW 1305 -- >
*/
var json = {
"contact1" : {
"fname": ["First Name:", "Aida"],
"lname": ["Last Name:", "Piedra"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "Elixir"],
"effects":["Effects:", "Delay"],
"curency":["Currency:", "Cash"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact2" : {
"fname": ["First Name:", "Betty"],
"lname": ["Last Name:", "Piedra"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "ErnieBall"],
"effects":["Effects:", "Distortion"],
"curency":["Currency:", "Credit"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact3" : {
"fname": ["First Name:", "Beatriz"],
"lname": ["Last Name:", "Oramas"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "DMustain"],
"strings":["Strings:", "Elixir"],
"effects":["Effects:", "Reverb"],
"curency":["Currency:", "Cash"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact4" : {
"fname": ["First Name:", "Aida Beatriz"],
"lname": ["Last Name:", "Piedra"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "Elixir"],
"effects":["Effects:", "Delay"],
"curency":["Currency:", "Cash"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact5" : {
"fname": ["First Name:", "Mom"],
"lname": ["Last Name:", "Piedra"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Gibson"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "ErnieBall"],
"effects":["Effects:", "Distortion"],
"curency":["Currency:", "Credit"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact6" : {
"fname": ["First Name:", "Julio"],
"lname": ["Last Name:", "Davila"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "Elixir"],
"effects":["Effects:", "Delay"],
"curency":["Currency:", "Cash"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact7" : {
"fname": ["First Name:", "Segundo"],
"lname": ["Last Name:", "Davila"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "ErnieBall"],
"effects":["Effects:", "Distortion"],
"curency":["Currency:", "Credit"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact8" : {
"fname": ["First Name:", "Gian"],
"lname": ["Last Name:", "Davila"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "Elixir"],
"effects":["Effects:", "Delay"],
"curency":["Currency:", "Cash"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact9" : {
"fname": ["First Name:", "Marcela"],
"lname": ["Last Name:", "Davila"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "ErnieBall"],
"effects":["Effects:", "Distortion"],
"curency":["Currency:", "Credit"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact10" : {
"fname": ["First Name:", "Violet"],
"lname": ["Last Name:", "Davila"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "DMustain"],
"strings":["Strings:", "Elixir"],
"effects":["Effects:", "Reverb"],
"curency":["Currency:", "Cash"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact11" : {
"fname": ["First Name:", "Eddy"],
"lname": ["Last Name:", "Davla"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "Elixir"],
"effects":["Effects:", "Delay"],
"curency":["Currency:", "Cash"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact12" : {
"fname": ["First Name:", "Aida"],
"lname": ["Last Name:", "Piedra"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "ErnieBall"],
"effects":["Effects:", "Distortion"],
"curency":["Currency:", "Credit"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact13" : {
"fname": ["First Name:", "Aida"],
"lname": ["Last Name:", "Piedra"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "Elixir"],
"effects":["Effects:", "Delay"],
"curency":["Currency:", "Cash"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact14" : {
"fname": ["First Name:", "Aida"],
"lname": ["Last Name:", "Piedra"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "ErnieBall"],
"effects":["Effects:", "Distortion"],
"curency":["Currency:", "Credit"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact15" : {
"fname": ["First Name:", "Aida"],
"lname": ["Last Name:", "Piedra"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "Elixir"],
"effects":["Effects:", "Delay"],
"curency":["Currency:", "Cash"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact16" : {
"fname": ["First Name:", "Aida"],
"lname": ["Last Name:", "Piedra"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "ErnieBall"],
"effects":["Effects:", "Distortion"],
"curency":["Currency:", "Credit"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact17" : {
"fname": ["First Name:", "Aida"],
"lname": ["Last Name:", "Piedra"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "DMustain"],
"strings":["Strings:", "Elixir"],
"effects":["Effects:", "Reverb"],
"curency":["Currency:", "Cash"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact18" : {
"fname": ["First Name:", "Aida"],
"lname": ["Last Name:", "Piedra"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "Elixir"],
"effects":["Effects:", "Delay"],
"curency":["Currency:", "Cash"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact19" : {
"fname": ["First Name:", "Aida"],
"lname": ["Last Name:", "Piedra"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "ErnieBall"],
"effects":["Effects:", "Distortion"],
"curency":["Currency:", "Credit"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
},
"contact20" : {
"fname": ["First Name:", "Aida"],
"lname": ["Last Name:", "Piedra"],
"email": ["Email:", "aidapiedra@heaven.com"],
"date" : ["Date:", "2013-05-01"],
"guitar":["Guitar:", "Ibanez"],
"store": ["Store:", "Guitar Center"],
"rating":["Rating:", "10"],
"pickups":["PickUps:", "EMG"],
"strings":["Strings:", "Elixir"],
"effects":["Effects:", "Delay"],
"curency":["Currency:", "Cash"],
"coupon":["Coupon:", "No"],
"comments":["Comments:", " Music Forever"]
}
}